"""Calibrate option-pricing models to deterministic option-chain data.

The example demonstrates the structured calibration layer for three common
workflows: a flat Black--Scholes--Merton volatility, a SABR smile, and a compact
Heston stochastic-volatility fit. The data are synthetic and offline so the
example is stable in tests and CI.
"""

from __future__ import annotations

import pandas as pd

import abaquant as aq
from examples._shared.output import configure_example_visuals, print_mapping, reset_example_visuals


def build_bsm_chain() -> pd.DataFrame:
    """Create a synthetic option chain generated by one flat BSM volatility."""
    spot_price = 100.0
    maturity_years = 1.0
    risk_free_rate = 0.03
    dividend_yield = 0.01
    volatility = 0.24
    rows = []
    for strike in (85.0, 95.0, 100.0, 105.0, 115.0):
        model = aq.BlackScholesMertonModel(
            spot_price,
            strike,
            maturity_years,
            risk_free_rate,
            volatility,
            dividend_yield,
        )
        rows.append(
            {
                "option_type": "call",
                "strike": strike,
                "market_price": model.call_price(),
                "implied_volatility": volatility,
                "spot_price": spot_price,
                "maturity_years": maturity_years,
                "open_interest": 100,
            }
        )
    return pd.DataFrame(rows)


def build_sabr_smile() -> pd.DataFrame:
    """Create a synthetic SABR implied-volatility smile."""
    forward_price = 100.0
    maturity_years = 1.0
    rows = []
    for strike in (80.0, 90.0, 100.0, 110.0, 120.0):
        implied_volatility = aq.SABRVolatilityModel(
            forward_price,
            strike,
            maturity_years,
            initial_volatility=0.32,
            elasticity_parameter=0.8,
            spot_forward_correlation=-0.2,
            volatility_of_volatility=0.55,
        ).implied_vol()
        rows.append(
            {
                "option_type": "call",
                "strike": strike,
                "implied_volatility": implied_volatility,
                "spot_price": 100.0,
                "forward_price": forward_price,
                "maturity_years": maturity_years,
                "open_interest": 100,
            }
        )
    return pd.DataFrame(rows)


def run_calibrations() -> dict[str, object]:
    """Fit BSM, SABR, and compact Heston calibrations."""
    bsm_result = aq.BSMFlatVolCalibration(
        build_bsm_chain(),
        spot_price=100.0,
        maturity_years=1.0,
        risk_free_rate=0.03,
        dividend_yield=0.01,
        objective="price",
    ).fit()
    sabr_result = aq.SABRSmileCalibration(
        build_sabr_smile(),
        forward_price=100.0,
        maturity_years=1.0,
        beta=0.8,
        initial_parameters={"alpha": 0.25, "rho": -0.1, "nu": 0.4},
    ).fit()
    heston_result = aq.HestonCalibration(
        build_bsm_chain().iloc[[1, 2, 3]],
        spot_price=100.0,
        maturity_years=1.0,
        risk_free_rate=0.03,
        dividend_yield=0.01,
        objective="iv",
        max_contracts=3,
        max_iter=2,
    ).fit()
    return {
        "bsm_flat_volatility": bsm_result.parameters["volatility"],
        "bsm_rmse": bsm_result.error,
        "sabr_alpha": sabr_result.parameters["alpha"],
        "sabr_rho": sabr_result.parameters["rho"],
        "sabr_nu": sabr_result.parameters["nu"],
        "heston_v0": heston_result.parameters["v0"],
        "heston_rmse": heston_result.error,
    }


def create_calibration_visuals() -> dict[str, str]:
    """Create model-versus-market and residual calibration figures."""
    output_directory = configure_example_visuals(subdirectory="derivative_calibration")
    bsm_result = aq.BSMFlatVolCalibration(
        build_bsm_chain(),
        spot_price=100.0,
        maturity_years=1.0,
        risk_free_rate=0.03,
        dividend_yield=0.01,
        objective="price",
    ).fit()
    sabr_result = aq.SABRSmileCalibration(
        build_sabr_smile(),
        forward_price=100.0,
        maturity_years=1.0,
        beta=0.8,
        initial_parameters={"alpha": 0.25, "rho": -0.1, "nu": 0.4},
    ).fit()
    figures = {
        "bsm_model_vs_market": bsm_result.visualize(
            chart="model_vs_market", filename="bsm_model_vs_market"
        ),
        "bsm_residuals": bsm_result.visualize(chart="residuals", filename="bsm_residuals"),
        "sabr_parameters": sabr_result.visualize(chart="parameters", filename="sabr_parameters"),
    }
    reset_example_visuals()
    return {name: type(figure).__name__ for name, figure in figures.items()} | {
        "output_directory": str(output_directory)
    }


def run() -> None:
    """Run the deterministic derivative-calibration example."""
    print_mapping("Derivative calibration", run_calibrations())
    try:
        print_mapping("Created calibration figures", create_calibration_visuals())
    except aq.VisualizationError as exc:
        print(f"Visualization skipped: {exc}")


if __name__ == "__main__":
    run()
